---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bggapi-hpa
  namespace: workshop04
spec:
  minReplicas: 1
  maxReplicas: 8
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: bggapi-ro
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
