---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-secret
  namespace: workshop3
spec:
  encryptedData:
    .dockerconfigjson: AgCHiT5zUMm7HfaRUK8uv0tDPsNv0+GBSqReeYuRweuJ07O0dCYy4/CHTTQZNW8u4WT7mAjT8j+AMQ9W46izDoT7NCwox7d2zSAqovmBkbICoLu+5wqjz3bVo79nk9RTltCbODTIUOAjUn/3gBnrT1Btd6c1h5nwghK1A2ppiitXiRuoBGp5iIQ1g50NDkhal7XrD+P4gyh85hU7PjnDvmboR0aX4Q/cDZBCOyzYDwKDbbrwUc+LQKyK9Ouro48KXIkEBcXWdQkzx15JH2+RbmSuKW6XO4p/EIkSx75sTwg4Oos7W063lWo+XoYYYNvoovy6foldEksbPSU71WrW7skYoOqtKHDHbHu0rgKBdXp/81lCi1KxksUoutdDMHYX84eNFNlNjkY9s9TEXj4nwPyhOI1wPfZWwE5AhTZhLLA0M8SAxWTlXW07g0bHdS+jwIzi78TGRg3EPzS48qJjVpQDq5tQqM8j7mNEPzgY7OPI5OADo23XFD+dfhyABf5hfTROtbWuhY3A/EPNCvF42BQ5sN0QsSB84I4+j+0yghg/jbOZBqn2yF3TyytIb1y1ij4o/woPPedRtrFUkThpNfBK4KEBDf4eOwoJdQ0SvlZ03diwUSmF7DErw71MIxsOlzJw6JVaDAloJNpGGvypix72EdpX3kAODA4YVOUbYvUK7QJ+lC66WI5azdYD25IZtxmZbyindrVeM89WKZbh41WWlaq3v+xduDJle3bGo9iopW33t9lPnPGGWNd/5R3w9sF4G2LwbX4//lc8qBWRA5hlXvky8XmQO0FyGzGZSWs2LLd9AXUzwgjm29oz0HHMCRmNRpAeya5KWbNk0f34Szyt1lLgR/7wiWgMgx3ekyu6ZRu9ixHoHpmq4wQdWfOVmj/aTV9yT/VVwA0X7N8QJqtqeiPWxM7GQqbz
  template:
    metadata:
      name: gitlab-registry-secret
      namespace: workshop3
    type: kubernetes.io/dockerconfigjson
